# Generated by Django 5.2.8 on 2025-12-14 17:56

import bboard.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_tag_bb_author_profile_bb_tags_bbtag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbtag',
            options={'verbose_name': 'Связь объявление–тег', 'verbose_name_plural': 'Связи объявление–тег'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='bb',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bbs', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(validators=[bboard.validators.validate_min_length_10], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(validators=[bboard.validators.validate_positive_price], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bbs', to='bboard.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=50, validators=[bboard.validators.validate_no_bad_words], verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='bbtag',
            name='bb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.bb', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='bbtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.tag', verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='bbtag',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Вес тега'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[bboard.validators.validate_phone_simple], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Название рубрики'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Тег'),
        ),
    ]
