# Generated by Django 5.2.8 on 2025-12-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_bbtag_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Цвет'),
        ),
    ]
