# Generated by Django 5.2.8 on 2025-12-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_rubric_description'),
        ('bboard', '0005_tag_color'),
    ]

    operations = [
    ]
