# Generated by Django 5.2.8 on 2025-12-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_merge_0005_rubric_description_0005_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='note',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Примечание'),
        ),
    ]
